[package]
name = "butterfly-rs"
version = "0.1.0"
authors = ["alanb <efik722life@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "0.13.1"
tokio = { version = "0.2.10", features = ["full"] }
serde = "1.0.104"
serde_derive = "1.0.104"
toml = "0.5.6"
